#!/usr/bin/env bash
# This script displays numbers from 1 to 20, displaying specific messages for superstitious numbers (4, 9, 17)

COUNT=1

while [ $COUNT -le 20 ]; do
    
    # Use case statement to check the value of the counter
    case $COUNT in
        4)
            echo "$COUNT"
            echo "bad luck from China"
            ;;
        9)
            echo "$COUNT"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$COUNT"
            echo "bad luck from Italy"
            ;;
        *)
            # Default action for all other numbers
            echo "$COUNT"
            ;;
    esac

    # Increment the counter
    COUNT=$((COUNT + 1))
done
