#!/usr/bin/env bash
# This script displays the time from 0:01 to 12:59 using nested while loops

HOUR=0

# Outer loop: Iterates hours from 0 to 12
while [ $HOUR -le 12 ]; do
    
    # Print the current hour label
    echo "Hour: $HOUR"
    
    MINUTE=1
    
    # Inner loop: Iterates minutes from 1 to 59
    while [ $MINUTE -le 59 ]; do
        echo "$MINUTE"
        MINUTE=$((MINUTE + 1))
    done
    
    # Increment the hour
    HOUR=$((HOUR + 1))
done
